#!/usr/bin/env python3
"""Generate Codex custom agents from Claude Code project sub-agents."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / ".claude" / "agents"
TARGET_DIR = ROOT / ".codex" / "agents"
NAME_PATTERN = re.compile(r"[a-z0-9-]+")
GENERATED_HEADER = "# Generated by scripts/sync-agents.py. Edit .claude/agents/*.md instead.\n"


def parse_agent(path: Path) -> tuple[str, str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: expected YAML frontmatter")

    try:
        frontmatter, instructions = text[4:].split("\n---\n", 1)
    except ValueError as error:
        raise ValueError(f"{path}: frontmatter is not closed") from error

    fields: dict[str, str] = {}
    for line in frontmatter.splitlines():
        if not line or line.startswith((" ", "\t")):
            continue
        key, separator, value = line.partition(":")
        if separator:
            fields[key.strip()] = value.strip()

    name = fields.get("name", "")
    description = fields.get("description", "")
    if not NAME_PATTERN.fullmatch(name):
        raise ValueError(f"{path}: name must use lowercase letters, digits, and hyphens")
    if not description:
        raise ValueError(f"{path}: description is required")
    if "'''" in instructions:
        raise ValueError(f"{path}: instructions cannot contain three consecutive apostrophes")

    return name, description, instructions.strip()


def render_codex_agent(name: str, description: str, instructions: str) -> str:
    return (
        GENERATED_HEADER
        + f"name = {json.dumps(name)}\n"
        f"description = {json.dumps(description)}\n"
        "developer_instructions = '''\n"
        f"{instructions}\n"
        "'''\n"
    )


def expected_outputs() -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for source in sorted(SOURCE_DIR.glob("*.md")):
        name, description, instructions = parse_agent(source)
        outputs[TARGET_DIR / f"{source.stem}.toml"] = render_codex_agent(
            name, description, instructions
        )
    return outputs


def check(outputs: dict[Path, str]) -> int:
    stale: list[Path] = []
    for path, expected in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path)

    unexpected = generated_files() - set(outputs)
    for path in stale:
        print(f"out of sync: {path.relative_to(ROOT)}", file=sys.stderr)
    for path in unexpected:
        print(f"unexpected generated file: {path.relative_to(ROOT)}", file=sys.stderr)
    return 1 if stale or unexpected else 0


def sync(outputs: dict[Path, str]) -> int:
    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8")
        print(f"updated {path.relative_to(ROOT)}")

    for path in sorted(generated_files() - set(outputs)):
        path.unlink()
        print(f"removed {path.relative_to(ROOT)}")
    return 0


def generated_files() -> set[Path]:
    generated: set[Path] = set()
    for path in TARGET_DIR.glob("*.toml"):
        if path.read_text(encoding="utf-8").startswith(GENERATED_HEADER):
            generated.add(path)
    return generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether generated Codex agents are current without editing files",
    )
    args = parser.parse_args()

    try:
        outputs = expected_outputs()
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    return check(outputs) if args.check else sync(outputs)


if __name__ == "__main__":
    raise SystemExit(main())
